-- Create TRANSACTION_INVOICE_WEIGHT_DETAILS table if it doesn't exist
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TRANSACTION_INVOICE_WEIGHT_DETAILS' AND xtype='U')
BEGIN
    CREATE TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS](
        [TRANRID] [int] IDENTITY(1,1) NOT NULL,
        [TRANMID] [int] NOT NULL,
        [PACKMID] [int] NOT NULL,
        [PACKTMID] [int] NOT NULL,
        [SLABVALUE] [numeric](18, 3) NOT NULL,
        [PNDSVALUE] [numeric](18, 3) NOT NULL,
        [TOTALPNDS] [numeric](18, 3) NOT NULL,
        [PACKWGT] [numeric](18, 3) NOT NULL,
        [TOTALWGHT] [numeric](18, 3) NOT NULL,
        [ONEDOLLAR] [numeric](18, 3) NOT NULL,
        [TOTALDOLVAL] [numeric](18, 3) NOT NULL,
        [WEIGHTINKGS] [numeric](18, 3) NOT NULL,
        [PERKGRATE] [numeric](18, 3) NOT NULL,
        [CUSRID] [varchar](100) NOT NULL,
        [LMUSRID] [varchar](100) NOT NULL,
        [DISPSTATUS] [smallint] NOT NULL,
        [PRCSDATE] [datetime] NOT NULL,
     CONSTRAINT [PK_TRANSACTION_INVOICE_WEIGHT_DETAILS] PRIMARY KEY CLUSTERED 
    (
        [TRANRID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

    PRINT 'TRANSACTION_INVOICE_WEIGHT_DETAILS table created successfully'
END
ELSE
BEGIN
    PRINT 'TRANSACTION_INVOICE_WEIGHT_DETAILS table already exists'
END

-- Add foreign key constraints if they don't exist
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANSACTIONMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANSACTIONMASTER] FOREIGN KEY([TRANMID])
    REFERENCES [dbo].[TRANSACTIONMASTER] ([TRANMID])
    
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] CHECK CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANSACTIONMASTER]
    PRINT 'Foreign key to TRANSACTIONMASTER added'
END

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGMASTER] FOREIGN KEY([PACKMID])
    REFERENCES [dbo].[PACKINGMASTER] ([PACKMID])
    
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] CHECK CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGMASTER]
    PRINT 'Foreign key to PACKINGMASTER added'
END

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGTYPEMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGTYPEMASTER] FOREIGN KEY([PACKTMID])
    REFERENCES [dbo].[PACKINGTYPEMASTER] ([PACKTMID])
    
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] CHECK CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGTYPEMASTER]
    PRINT 'Foreign key to PACKINGTYPEMASTER added'
END

-- Create indexes for better performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANMID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANMID] ON [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]
    (
        [TRANMID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    PRINT 'Index on TRANMID created'
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKMID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKMID] ON [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]
    (
        [PACKMID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    PRINT 'Index on PACKMID created'
END

PRINT 'TRANSACTION_INVOICE_WEIGHT_DETAILS table setup completed successfully!'
