USE [KVM_ERP]
GO

-- Safely add FACAVGWGT and FACAVGCOUNT columns to TRANSACTION_PRODUCT_CALCULATION
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TRANSACTION_PRODUCT_CALCULATION' 
                 AND COLUMN_NAME = 'FACAVGWGT')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_PRODUCT_CALCULATION]
    ADD [FACAVGWGT] NUMERIC(18,3) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TRANSACTION_PRODUCT_CALCULATION' 
                 AND COLUMN_NAME = 'FACAVGCOUNT')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_PRODUCT_CALCULATION]
    ADD [FACAVGCOUNT] NUMERIC(18,3) NULL;
END
GO


