-- Create TRANSACTION_QUALITY_CHECK table
-- This table stores quality check information for raw material intake transactions

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TRANSACTION_QUALITY_CHECK' AND xtype='U')
BEGIN
    CREATE TABLE [dbo].[TRANSACTION_QUALITY_CHECK](
        [TRANQID] [int] IDENTITY(1,1) NOT NULL,
        [TRANMID] [int] NOT NULL,
        [LABOID] [int] NOT NULL,
        [STATUS] [int] NOT NULL,
        [REMARKS] [varchar](max) NOT NULL,
        [DONEBY] [varchar](100) NOT NULL,
        [VERIFIEDBY] [varchar](100) NOT NULL,
        [LOTDATE] [datetime] NOT NULL,
        [CUSRID] [varchar](100) NULL,
        [LMUSRID] [varchar](100) NULL,
        [DISPSTATUS] [smallint] NULL,
        [PRCSDATE] [datetime] NULL,
        CONSTRAINT [PK_TRANSACTION_QUALITY_CHECK] PRIMARY KEY CLUSTERED 
        (
            [TRANQID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

    PRINT 'TRANSACTION_QUALITY_CHECK table created successfully'
END
ELSE
BEGIN
    PRINT 'TRANSACTION_QUALITY_CHECK table already exists'
END

-- Add foreign key constraints if they don't exist
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_QUALITY_CHECK_TRANSACTIONMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_QUALITY_CHECK]  WITH CHECK ADD  
    CONSTRAINT [FK_TRANSACTION_QUALITY_CHECK_TRANSACTIONMASTER] FOREIGN KEY([TRANMID])
    REFERENCES [dbo].[TRANSACTIONMASTER] ([TRANMID])
    ON DELETE CASCADE
    
    ALTER TABLE [dbo].[TRANSACTION_QUALITY_CHECK] CHECK CONSTRAINT [FK_TRANSACTION_QUALITY_CHECK_TRANSACTIONMASTER]
    PRINT 'Foreign key constraint to TRANSACTIONMASTER added'
END

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_QUALITY_CHECK_LABORATORYMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_QUALITY_CHECK]  WITH CHECK ADD  
    CONSTRAINT [FK_TRANSACTION_QUALITY_CHECK_LABORATORYMASTER] FOREIGN KEY([LABOID])
    REFERENCES [dbo].[LABORATORYMASTER] ([LABOID])
    
    ALTER TABLE [dbo].[TRANSACTION_QUALITY_CHECK] CHECK CONSTRAINT [FK_TRANSACTION_QUALITY_CHECK_LABORATORYMASTER]
    PRINT 'Foreign key constraint to LABORATORYMASTER added'
END

-- Set default values for new records
IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_QUALITY_CHECK_DISPSTATUS')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_QUALITY_CHECK] ADD CONSTRAINT [DF_TRANSACTION_QUALITY_CHECK_DISPSTATUS] DEFAULT ((0)) FOR [DISPSTATUS]
    PRINT 'Default constraint for DISPSTATUS added'
END

PRINT 'TRANSACTION_QUALITY_CHECK table setup completed successfully'
