-- Find the correct table name for group-role assignments

-- List all tables with 'Group' or 'Role' in the name
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Group%' 
   OR TABLE_NAME LIKE '%Role%'
ORDER BY TABLE_NAME;

-- Check which tables might have GroupId and RoleId columns
SELECT 
    t.TABLE_NAME,
    c1.COLUMN_NAME AS Column1,
    c2.COLUMN_NAME AS Column2
FROM INFORMATION_SCHEMA.TABLES t
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c1 ON t.TABLE_NAME = c1.TABLE_NAME AND c1.COLUMN_NAME LIKE '%GroupId%'
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c2 ON t.TABLE_NAME = c2.TABLE_NAME AND c2.COLUMN_NAME LIKE '%RoleId%'
WHERE (c1.COLUMN_NAME IS NOT NULL OR c2.COLUMN_NAME IS NOT NULL)
  AND t.TABLE_TYPE = 'BASE TABLE'
ORDER BY t.TABLE_NAME;

-- THIS WILL TELL US THE EXACT TABLE NAME!
